name: Build on Release

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Install dependencies
      run: deno install

    - name: check codes
      run: deno check main.ts

    # - name: Run tests
    #   run: deno test

    - name: Run build
      run: |
        deno compile --output=dist/ez --target=x86_64-pc-windows-msvc -A main.ts
        zip -j dist/ez-windows-x64.zip dist/ez.exe

        deno compile --output=dist/ez --target=x86_64-unknown-linux-gnu -A main.ts
        tar -czvf dist/ez-linux-x64.tar.gz dist/ez

        deno compile --output=dist/ez --target=aarch64-unknown-linux-gnu -A main.ts
        tar -czvf dist/ez-linux-arm64.tar.gz dist/ez

        deno compile --output=dist/ez --target=x86_64-apple-darwin -A main.ts
        tar -czvf dist/ez-macos-x64.tar.gz dist/ez

        deno compile --output=dist/ez --target=aarch64-apple-darwin -A main.ts
        tar -czvf dist/ez-macos-arm64.tar.gz dist/ez

        rm dist/ez && rm dist/ez.exe


    - name: release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*